# get_geno
#
#' Get genotype at a single position
#'
#' With data on the continuous crossover location information produced by
#' sim_from_pedigree, grab the genotype at a given position.
#'
#' @param xodat The sort of detailed genotype/XO data generated by
#' \code{\link{sim_from_pedigree}}
#' @param position Position (in cM) for which to obtain genotypes
#'
#' @return A numeric matrix with two columns: the maternal and
#' paternal allele for each individual.
#'
#' @export
#' @keywords utilities
#' @seealso \code{\link{sim_from_pedigree}}, \code{\link{convert2geno}}
#'
#' @examples
#' # simulate AIL pedigree
#' tab <- sim_ail_pedigree(12, 30)
#' # simulate data from that pedigree
#' dat <- sim_from_pedigree(tab)
#' # get genotype at position 30 cM
#' geno <- get_geno(dat, 30)
get_geno <-
function(xodat, position)
{
  if(position < 0 || position > max(xodat[[1]][[1]][1,]))
    stop("position is outside the range of the data")
  if(position == 0) position <- -1
  if(position == max(xodat[[1]][[1]][1,])) position <- position - 0.001

  output <- matrix(ncol=2, nrow=length(xodat))

  for(i in seq(along=xodat)) {
    for(j in 1:2) {
      dat <- xodat[[i]][[j]]

      wh <- which(dat[1,] <= position)
      output[i,j] <- ifelse(length(wh) > 0, dat[2, max(wh)+1], dat[2,1])
    }
  }

  dimnames(output) <- list(names(xodat), c("mat", "pat"))

  output
}
