# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fromR_convert2geno <- function(xodat, map, founder_geno) {
    .Call('simcross_fromR_convert2geno', PACKAGE = 'simcross', xodat, map, founder_geno)
}

fromR_convert2genoarray <- function(xodat, map) {
    .Call('simcross_fromR_convert2genoarray', PACKAGE = 'simcross', xodat, map)
}

fromR_get_geno <- function(xodat, position) {
    .Call('simcross_fromR_get_geno', PACKAGE = 'simcross', xodat, position)
}

random_int <- function(n, low, high) {
    .Call('simcross_random_int', PACKAGE = 'simcross', n, low, high)
}

fromR_sim_crossovers <- function(L, m, p, obligate_chiasma, Lstar) {
    .Call('simcross_fromR_sim_crossovers', PACKAGE = 'simcross', L, m, p, obligate_chiasma, Lstar)
}

fromR_sim_meiosis <- function(parent, m, p, obligate_chiasma, Lstar) {
    .Call('simcross_fromR_sim_meiosis', PACKAGE = 'simcross', parent, m, p, obligate_chiasma, Lstar)
}

