# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fromR_convert2geno <- function(xodat, map, founder_geno) {
    .Call('simcross_fromR_convert2geno', PACKAGE = 'simcross', xodat, map, founder_geno)
}

fromR_get_geno <- function(xodat, position) {
    .Call('simcross_fromR_get_geno', PACKAGE = 'simcross', xodat, position)
}

fromR_sim_crossovers <- function(L, m = 10L, p = 0.0) {
    .Call('simcross_fromR_sim_crossovers', PACKAGE = 'simcross', L, m, p)
}

fromR_sim_meiosis <- function(parent, m = 10L, p = 0.0) {
    .Call('simcross_fromR_sim_meiosis', PACKAGE = 'simcross', parent, m, p)
}

